### PR TITLE
Added dependencie informations

### PR DESCRIPTION
**Pull request by buhtz**
Your cmake script isn't very talkative. I invested a lot of time to find the correct packages.

This was done an a vanilla Debian 11.

### CODE REVIEW

**Comment by loimu** [comment]
What do you think about changing spelling a bit?

> Maybe you'll have to install these dependencies

**Comment by buhtz** [comment]
You are the maintainer. It is up to you to modify PRs or review them.
No problem with that.

**Comment by Xeno-Idaltu** [comment]
Since submitting bugs is not an option I'm gonna post it here.

Enhancement Wish:
1) Add AM/PM option
2) Allow loop/repeat of sounds.


As for naming the app. I think naming it something like qCron, qAlarm, etc makes more sense, otherwise it will be forgotten and not many people would know of it.

**Comment by loimu** [comment]
@Xeno-Idaltu as an issue/bug tracker I'm using launchpad, unfortunately it requires registering an account
https://bugs.launchpad.net/zeit

**Comment by loimu** [comment]
Fixed in 07b7621

**Pull request closed without merging**
